[2024-06-10T22:52:03.364+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: print_context_dag.print_context manual__2024-06-10T22:52:02.386524+00:00 [queued]>
[2024-06-10T22:52:03.368+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: print_context_dag.print_context manual__2024-06-10T22:52:02.386524+00:00 [queued]>
[2024-06-10T22:52:03.368+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-06-10T22:52:03.368+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-06-10T22:52:03.368+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-06-10T22:52:03.374+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): print_context> on 2024-06-10 22:52:02.386524+00:00
[2024-06-10T22:52:03.376+0000] {standard_task_runner.py:55} INFO - Started process 170 to run task
[2024-06-10T22:52:03.378+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'print_context_dag', 'print_context', 'manual__2024-06-10T22:52:02.386524+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/print_context_dag.py', '--cfg-path', '/tmp/tmph26aagc3']
[2024-06-10T22:52:03.379+0000] {standard_task_runner.py:83} INFO - Job 115: Subtask print_context
[2024-06-10T22:52:03.406+0000] {task_command.py:376} INFO - Running <TaskInstance: print_context_dag.print_context manual__2024-06-10T22:52:02.386524+00:00 [running]> on host 086bd2810b7c
[2024-06-10T22:52:03.436+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=print_context_dag
AIRFLOW_CTX_TASK_ID=print_context
AIRFLOW_CTX_EXECUTION_DATE=2024-06-10T22:52:02.386524+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-10T22:52:02.386524+00:00
[2024-06-10T22:52:03.436+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/print_context_dag.py", line 11, in print_context
    fq = kwargs['params']['query']
KeyError: 'query'
[2024-06-10T22:52:03.440+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=print_context_dag, task_id=print_context, execution_date=20240610T225202, start_date=20240610T225203, end_date=20240610T225203
[2024-06-10T22:52:03.445+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 115 for task print_context ('query'; 170)
[2024-06-10T22:52:03.470+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-06-10T22:52:03.479+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
