[2024-06-11T05:08:33.497+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: example_callback.task3 manual__2024-06-11T05:08:31.208817+00:00 [queued]>
[2024-06-11T05:08:33.502+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: example_callback.task3 manual__2024-06-11T05:08:31.208817+00:00 [queued]>
[2024-06-11T05:08:33.502+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-06-11T05:08:33.502+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-06-11T05:08:33.502+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-06-11T05:08:33.508+0000] {taskinstance.py:1383} INFO - Executing <Task(EmptyOperator): task3> on 2024-06-11 05:08:31.208817+00:00
[2024-06-11T05:08:33.511+0000] {standard_task_runner.py:55} INFO - Started process 2234 to run task
[2024-06-11T05:08:33.513+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_callback', 'task3', 'manual__2024-06-11T05:08:31.208817+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/callback_example.py', '--cfg-path', '/tmp/tmpreuiwqim']
[2024-06-11T05:08:33.514+0000] {standard_task_runner.py:83} INFO - Job 121: Subtask task3
[2024-06-11T05:08:33.543+0000] {task_command.py:376} INFO - Running <TaskInstance: example_callback.task3 manual__2024-06-11T05:08:31.208817+00:00 [running]> on host 8a665be84819
[2024-06-11T05:08:33.572+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_callback
AIRFLOW_CTX_TASK_ID=task3
AIRFLOW_CTX_EXECUTION_DATE=2024-06-11T05:08:31.208817+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-11T05:08:31.208817+00:00
[2024-06-11T05:08:33.576+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=example_callback, task_id=task3, execution_date=20240611T050831, start_date=20240611T050833, end_date=20240611T050833
[2024-06-11T05:08:33.576+0000] {taskinstance.py:1619} ERROR - Error when executing on_success callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1617, in _run_finished_callback
    callback(context)
TypeError: 'list' object is not callable
[2024-06-11T05:08:33.605+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-06-11T05:08:33.614+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
