[2024-06-22T15:23:30.491+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dynamic_tasks_dag.task_6 manual__2024-06-22T15:23:23.180483+00:00 [queued]>
[2024-06-22T15:23:30.496+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dynamic_tasks_dag.task_6 manual__2024-06-22T15:23:23.180483+00:00 [queued]>
[2024-06-22T15:23:30.496+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-06-22T15:23:30.496+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2024-06-22T15:23:30.496+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-06-22T15:23:30.502+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): task_6> on 2024-06-22 15:23:23.180483+00:00
[2024-06-22T15:23:30.505+0000] {standard_task_runner.py:55} INFO - Started process 3379 to run task
[2024-06-22T15:23:30.507+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dynamic_tasks_dag', 'task_6', 'manual__2024-06-22T15:23:23.180483+00:00', '--job-id', '1294', '--raw', '--subdir', 'DAGS_FOLDER/dynamic_tasks.py', '--cfg-path', '/tmp/tmpofl0a0a6']
[2024-06-22T15:23:30.507+0000] {standard_task_runner.py:83} INFO - Job 1294: Subtask task_6
[2024-06-22T15:23:30.537+0000] {task_command.py:376} INFO - Running <TaskInstance: dynamic_tasks_dag.task_6 manual__2024-06-22T15:23:23.180483+00:00 [running]> on host 5f0aa929f7fe
[2024-06-22T15:23:30.570+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dynamic_tasks_dag
AIRFLOW_CTX_TASK_ID=task_6
AIRFLOW_CTX_EXECUTION_DATE=2024-06-22T15:23:23.180483+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-22T15:23:23.180483+00:00
[2024-06-22T15:23:30.570+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-06-22T15:23:30.571+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-06-22T15:23:30.576+0000] {subprocess.py:86} INFO - Output:
[2024-06-22T15:23:30.577+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-22T15:23:30.582+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-22T15:23:30.584+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dynamic_tasks_dag, task_id=task_6, execution_date=20240622T152323, start_date=20240622T152330, end_date=20240622T152330
[2024-06-22T15:23:30.590+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1294 for task task_6 (Bash command failed. The command returned a non-zero exit code 1.; 3379)
[2024-06-22T15:23:30.599+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-06-22T15:23:30.613+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
